#!/usr/bin/env bash

LIBRARY_TYPE=${1:-0}
BUILD_CONFIG=${2:-RelWithDebInfo}
BUILD_DIR=${3:-build}

PROFILER_STATIC_LIB="OFF"
PROFILER_SHARED_LIB="OFF"

# Profiler Implementation
if [ "$LIBRARY_TYPE" -eq "1" ] ; then
    PROFILER_STATIC_LIB="ON"
fi

if [ "$LIBRARY_TYPE" -eq "2" ] ; then
    PROFILER_STATIC_LIB="ON"
    PROFILER_SHARED_LIB="ON"
fi

mkdir -p $BUILD_DIR
echo "cmake -G \"Unix Makefiles\" -DCMAKE_BUILD_TYPE=$BUILD_CONFIG -DPROFILER_BUILD_STATIC_LIBS=$PROFILER_STATIC_LIB -DPROFILER_BUILD_SHARED_LIBS=$PROFILER_SHARED_LIB -S ./liquidfun/Box2D -B$BUILD_DIR"
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_CONFIG -DPROFILER_BUILD_STATIC_LIBS=$PROFILER_STATIC_LIB -DPROFILER_BUILD_SHARED_LIBS=$PROFILER_SHARED_LIB -S ./liquidfun/Box2D -B$BUILD_DIR 

cmake --build ./$BUILD_DIR --target Testbed --config %BUILD_CONFIG%
