@echo off

set LIBRARY_TYPE=%1
set BUILD_CONFIG=%2
set BUILD_DIR=%3

set PROFILER_STATIC_LIB="OFF"
set PROFILER_SHARED_LIB="OFF"

IF NOT DEFINED LIBRARY_TYPE (SET LIBRARY_TYPE=0) 
IF NOT DEFINED BUILD_CONFIG (SET BUILD_CONFIG="RelWithDebInfo") 
IF NOT DEFINED BUILD_DIR (SET BUILD_DIR="build") 

IF %LIBRARY_TYPE%==1 (
    set PROFILER_STATIC_LIB="ON"
)
IF %LIBRARY_TYPE%==2 (
    set PROFILER_STATIC_LIB="ON"
    set PROFILER_SHARED_LIB="ON"
)

echo cmake -G "Visual Studio 16 2019" -A x64 -DPROFILER_BUILD_STATIC_LIBS=%PROFILER_STATIC_LIB% -DPROFILER_BUILD_SHARED_LIBS=%PROFILER_SHARED_LIB% -S ./liquidfun/Box2D -B ./%BUILD_DIR%
cmake -G "Visual Studio 16 2019" -A x64 -DPROFILER_BUILD_STATIC_LIBS=%PROFILER_STATIC_LIB% -DPROFILER_BUILD_SHARED_LIBS=%PROFILER_SHARED_LIB% -S ./liquidfun/Box2D -B ./%BUILD_DIR%

cmake --build ./%BUILD_DIR% --target Testbed --config %BUILD_CONFIG%
